# Generated by Django 5.2.7 on 2025-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='title',
            field=models.CharField(default='Untitled Activity', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='duration_minutes',
        ),
    ]
